"""Research pipeline stage definitions."""

from enum import Enum


class PipelineStage(str, Enum):
    """Stages of the research and curation pipeline."""

    LOAD_CONFIG = "LOAD_CONFIG"
    REFRESH_CURRICULUM = "REFRESH_CURRICULUM"
    GENERATE_QUERIES = "GENERATE_QUERIES"
    SEARCH_DISCOVERY = "SEARCH_DISCOVERY"
    NORMALIZE_CANDIDATES = "NORMALIZE_CANDIDATES"
    EVALUATE_SOURCES = "EVALUATE_SOURCES"
    CHECK_ACCESS_POLICY = "CHECK_ACCESS_POLICY"
    FETCH_PAGES = "FETCH_PAGES"
    CACHE_SNAPSHOTS = "CACHE_SNAPSHOTS"
    EXTRACT_METADATA = "EXTRACT_METADATA"
    RESOLVE_DATES = "RESOLVE_DATES"
    EXTRACT_QUESTIONS = "EXTRACT_QUESTIONS"
    NORMALIZE_QUESTIONS = "NORMALIZE_QUESTIONS"
    CLASSIFY_CURRICULUM = "CLASSIFY_CURRICULUM"
    CONTENT_SAFETY_REVIEW = "CONTENT_SAFETY_REVIEW"
    VERIFY_ANSWERS = "VERIFY_ANSWERS"
    DEDUPLICATE = "DEDUPLICATE"
    SCORE_QUALITY = "SCORE_QUALITY"
    PERSIST_DATABASE = "PERSIST_DATABASE"
    UPDATE_FTS5 = "UPDATE_FTS5"
    RUN_AUDIT = "RUN_AUDIT"
    GENERATE_REPORT = "GENERATE_REPORT"
