"""Domain 1: Cloud Concepts Templates."""

CLOUD_CONCEPTS_TEMPLATES = [
    {
        "id": "CC_01",
        "stem": "Which benefit of the AWS Cloud refers to the ability to automatically grow or shrink computing resources in response to changing demand?",
        "correct": "Elasticity",
        "distractors": ["High availability", "Durability", "Agility"],
        "explanation": "Elasticity is the ability to acquire resources as you need them and release resources when you no longer need them.",
        "domain": 1,
        "domain_name": "Cloud Concepts",
        "task": "1.1",
        "services": [],
        "topics": ["Cloud Economics", "Elasticity"],
        "aws_source": "https://docs.aws.amazon.com/whitepapers/latest/aws-overview/six-advantages-of-cloud-computing.html",
    },
    {
        "id": "CC_02",
        "stem": "Which pillar of the AWS Well-Architected Framework focuses on structured processes to run workloads effectively and continuously improve supporting processes?",
        "correct": "Operational Excellence",
        "distractors": ["Security", "Reliability", "Performance Efficiency"],
        "explanation": "The Operational Excellence pillar focuses on running and monitoring systems, and continually improving processes and procedures.",
        "domain": 1,
        "domain_name": "Cloud Concepts",
        "task": "1.2",
        "services": ["AWS Well-Architected Tool"],
        "topics": ["Well-Architected Framework", "Operational Excellence"],
        "aws_source": "https://docs.aws.amazon.com/wellarchitected/latest/framework/operational-excellence.html",
    },
    {
        "id": "CC_03",
        "stem": "Which migration strategy (from the 7 Rs) involves moving applications to AWS without making any changes to the core application code or architecture ('lift and shift')?",
        "correct": "Rehost",
        "distractors": ["Refactor", "Replatform", "Repurchase"],
        "explanation": "Rehost (also known as 'lift and shift') moves applications to the cloud without code modification.",
        "domain": 1,
        "domain_name": "Cloud Concepts",
        "task": "1.3",
        "services": ["AWS Application Migration Service"],
        "topics": ["Cloud Migration", "7 Rs"],
        "aws_source": "https://docs.aws.amazon.com/whitepapers/latest/aws-migration-whitepaper/migration-strategies.html",
    },
    {
        "id": "CC_04",
        "stem": "How does adopting the AWS Cloud change an organization's financial model regarding capital expenditures (CapEx) and operational expenditures (OpEx)?",
        "correct": "It trades upfront capital expenses (CapEx) for low variable operational expenses (OpEx).",
        "distractors": [
            "It increases capital expenses (CapEx) to purchase dedicated data center hardware.",
            "It eliminates operational expenses (OpEx) entirely.",
            "It requires fixed 5-year capital equipment purchase commitments.",
        ],
        "explanation": "One of the core cloud financial advantages is trading heavy upfront capital expenses for pay-as-you-go variable operational expenses.",
        "domain": 1,
        "domain_name": "Cloud Concepts",
        "task": "1.4",
        "services": [],
        "topics": ["Cloud Economics", "CapEx vs OpEx"],
        "aws_source": "https://docs.aws.amazon.com/whitepapers/latest/aws-overview/six-advantages-of-cloud-computing.html",
    },
]
