"""Domain 2: Security and Compliance Templates."""

SECURITY_TEMPLATES = [
    {
        "id": "SEC_01",
        "stem": "Under the AWS Shared Responsibility Model, which of the following is an explicit responsibility of the customer when running an Amazon EC2 instance?",
        "correct": "Installing operating system security patches and configuring guest firewall rules.",
        "distractors": [
            "Maintaining physical security of the data center facilities.",
            "Decommissioning worn-out server storage drives and hardware.",
            "Patching the virtualization hypervisor layer.",
        ],
        "explanation": "Customers are responsible for 'Security IN the Cloud', including guest OS patching, application software, and network firewalls.",
        "domain": 2,
        "domain_name": "Security and Compliance",
        "task": "2.1",
        "services": ["Amazon EC2"],
        "topics": ["Shared Responsibility Model", "Security IN the Cloud"],
        "aws_source": "https://aws.amazon.com/compliance/shared-responsibility-model/",
    },
    {
        "id": "SEC_02",
        "stem": "Which AWS portal provides on-demand access to AWS compliance documentation, SOC reports, and PCI DSS compliance packages?",
        "correct": "AWS Artifact",
        "distractors": ["AWS Secrets Manager", "AWS Trusted Advisor", "Amazon GuardDuty"],
        "explanation": "AWS Artifact is the central compliance reporting portal for downloading security compliance agreements and audit documents.",
        "domain": 2,
        "domain_name": "Security and Compliance",
        "task": "2.2",
        "services": ["AWS Artifact"],
        "topics": ["Compliance", "Governance"],
        "aws_source": "https://aws.amazon.com/artifact/",
    },
    {
        "id": "SEC_03",
        "stem": "What is the recommended security best practice for managing user permissions in AWS Identity and Access Management (IAM)?",
        "correct": "Grant least privilege permissions by granting only the minimum access required for the task.",
        "distractors": [
            "Use the root account for all daily administrative tasks.",
            "Assign full administrator privileges to all newly created users.",
            "Share access keys across all developers on the team.",
        ],
        "explanation": "The principle of least privilege ensures identities are granted only permissions strictly necessary to perform their duties.",
        "domain": 2,
        "domain_name": "Security and Compliance",
        "task": "2.3",
        "services": ["AWS IAM"],
        "topics": ["IAM", "Least Privilege"],
        "aws_source": "https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html",
    },
    {
        "id": "SEC_04",
        "stem": "Which AWS security service uses machine learning to automatically analyze CloudTrail management events and VPC Flow Logs to detect anomalous account behavior and unauthorized access?",
        "correct": "Amazon GuardDuty",
        "distractors": ["AWS Shield Standard", "AWS WAF", "AWS KMS"],
        "explanation": "Amazon GuardDuty is an intelligent threat detection service that continuously monitors AWS accounts and workloads.",
        "domain": 2,
        "domain_name": "Security and Compliance",
        "task": "2.4",
        "services": ["Amazon GuardDuty"],
        "topics": ["Threat Detection", "Security Monitoring"],
        "aws_source": "https://aws.amazon.com/guardduty/",
    },
]
