"""Domain 3: Cloud Technology and Services Templates."""

TECHNOLOGY_TEMPLATES = [
    {
        "id": "TECH_01",
        "stem": "Which AWS infrastructure component consists of one or more discrete data centers, each with redundant power, networking, and connectivity, housed in separate facilities?",
        "correct": "Availability Zone (AZ)",
        "distractors": ["Edge Location", "AWS Region", "Local Zone"],
        "explanation": "An Availability Zone (AZ) is one or more discrete data centers with redundant power, networking, and connectivity in an AWS Region.",
        "domain": 3,
        "domain_name": "Cloud Technology and Services",
        "task": "3.2",
        "services": ["AWS Global Infrastructure"],
        "topics": ["Global Infrastructure", "Availability Zones"],
        "aws_source": "https://aws.amazon.com/about-aws/global-infrastructure/regions_az/",
    },
    {
        "id": "TECH_02",
        "stem": "A company wants to run code without provisioning, managing, or scaling virtual servers, and only pay for compute time consumed during execution. Which compute service fits this requirement?",
        "correct": "AWS Lambda",
        "distractors": ["Amazon EC2", "Amazon Lightsail", "AWS Outposts"],
        "explanation": "AWS Lambda is a serverless compute service that lets you run code without provisioning or managing servers.",
        "domain": 3,
        "domain_name": "Cloud Technology and Services",
        "task": "3.3",
        "services": ["AWS Lambda"],
        "topics": ["Serverless", "Compute"],
        "aws_source": "https://aws.amazon.com/lambda/",
    },
    {
        "id": "TECH_03",
        "stem": "Which AWS database service is fully managed, serverless, and provides single-digit millisecond latency at any scale for key-value and document data models?",
        "correct": "Amazon DynamoDB",
        "distractors": ["Amazon RDS", "Amazon Aurora", "Amazon Redshift"],
        "explanation": "Amazon DynamoDB is a fast and flexible NoSQL database service for all applications requiring consistent, single-digit millisecond latency.",
        "domain": 3,
        "domain_name": "Cloud Technology and Services",
        "task": "3.4",
        "services": ["Amazon DynamoDB"],
        "topics": ["NoSQL", "Databases"],
        "aws_source": "https://aws.amazon.com/dynamodb/",
    },
    {
        "id": "TECH_04",
        "stem": "Which Amazon S3 storage class is best suited for archiving data that is rarely accessed, requires minutes to hours for retrieval, and demands the lowest storage cost?",
        "correct": "Amazon S3 Glacier Flexible Retrieval",
        "distractors": ["Amazon S3 Standard", "Amazon S3 Intelligent-Tiering", "Amazon S3 Standard-IA"],
        "explanation": "Amazon S3 Glacier Flexible Retrieval provides low-cost archival storage for data that is infrequently accessed and can tolerate retrieval times of minutes to hours.",
        "domain": 3,
        "domain_name": "Cloud Technology and Services",
        "task": "3.6",
        "services": ["Amazon S3"],
        "topics": ["Object Storage", "S3 Glacier"],
        "aws_source": "https://aws.amazon.com/s3/storage-classes/",
    },
]
